//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace stoktakip.HelperClasses
{
	/// <summary>Field Creation Class for entity CategoryEntity</summary>
	public partial class CategoryFields
	{
		/// <summary>Creates a new CategoryEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Id); }}
		/// <summary>Creates a new CategoryEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CategoryFieldIndex.Name); }}
	}

	/// <summary>Field Creation Class for entity ProductEntity</summary>
	public partial class ProductFields
	{
		/// <summary>Creates a new ProductEntity.CategoryId field instance</summary>
		public static EntityField2 CategoryId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.CategoryId); }}
		/// <summary>Creates a new ProductEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Id); }}
		/// <summary>Creates a new ProductEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.Name); }}
		/// <summary>Creates a new ProductEntity.PurchasePrice field instance</summary>
		public static EntityField2 PurchasePrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.PurchasePrice); }}
		/// <summary>Creates a new ProductEntity.SalePrice field instance</summary>
		public static EntityField2 SalePrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.SalePrice); }}
		/// <summary>Creates a new ProductEntity.StockAmount field instance</summary>
		public static EntityField2 StockAmount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ProductFieldIndex.StockAmount); }}
	}

	/// <summary>Field Creation Class for entity StockTransactionEntity</summary>
	public partial class StockTransactionFields
	{
		/// <summary>Creates a new StockTransactionEntity.Amount field instance</summary>
		public static EntityField2 Amount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockTransactionFieldIndex.Amount); }}
		/// <summary>Creates a new StockTransactionEntity.Description field instance</summary>
		public static EntityField2 Description { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockTransactionFieldIndex.Description); }}
		/// <summary>Creates a new StockTransactionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockTransactionFieldIndex.Id); }}
		/// <summary>Creates a new StockTransactionEntity.ProductId field instance</summary>
		public static EntityField2 ProductId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockTransactionFieldIndex.ProductId); }}
		/// <summary>Creates a new StockTransactionEntity.TransactionDate field instance</summary>
		public static EntityField2 TransactionDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockTransactionFieldIndex.TransactionDate); }}
		/// <summary>Creates a new StockTransactionEntity.TransactionType field instance</summary>
		public static EntityField2 TransactionType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(StockTransactionFieldIndex.TransactionType); }}
	}
	

}